version: "3.0"

services:
  mysqlService:
    image: mysql:8.0.13
    restart: always
    privileged: true
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init_connect='SET collation_connection = utf8_unicode_ci' --init-connect='SET NAMES UTF8MB4;' --sql-mode="NO_ENGINE_SUBSTITUTION" --innodb-flush-log-at-trx-commit=0
    env_file:
      - .env
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Asia/Shanghai
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306

  redisService:
    image: redis:5.0
    env_file:
      - .env
    container_name: ${REDIS_CONTAINER_NAME}
    command: redis-server --requirepass ${REDIS_PASSWD} --appendonly yes --appendfsync everysec
    restart: always
    privileged: true
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_DIR}:/data

  mongoServer:
    image: mongo:3.4
    container_name: ${MONGO_CONTAINER_NAME}
    privileged: true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    restart: always
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
      - ${MONGO_BACK_DATA_DIR}:/data/backup
     # - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/
    command: mongod  --auth

  rabbitmq:
    #容器名称
    container_name: ${RABBITMQ_CONTAINER_NAME}
    privileged: true
    #镜像名称
    build: .
    #总是重启后启动
    restart: always
    #端口映射
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_PORT_ADMIN}:15672
    #挂载
    volumes:
      - ${RABBITMQ_DATA_DIR}:/var/lib/rabbitmq
    #环境变量
    environment:
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_ROOT_NAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_ROOT_PASSWORD}
